CREATE TABLE SETTINGS(
    KEY TEXT PRIMARY KEY NOT NULL,
    VALUE TEXT NOT NULL
);

CREATE TABLE CHRISTIANS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    IMAGE TEXT,
    IN_JAIL INTEGER NOT NULL
);

CREATE TABLE COPS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    IMAGE TEXT
);

CREATE TABLE GAMES(
    ID INTEGER PRIMARY KEY NOT NULL,
    JAIL_START INTEGER NOT NULL,
    JAIL_INCREMENT INTEGER NOT NULL DEFAULT 0,
    JAIL_MAX INTEGER NOT NULL,
    START_TIME TEXT,
    END_TIME TEXT,
    RESULT_CALCULATED INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE CAPTURES(
    ID INTEGER PRIMARY KEY NOT NULL,
    GAME_ID INTEGER NOT NULL,
    CHRISTIAN_ID INTEGER,
    COP_ID INTEGER,
    CAPTURE_TIME TEXT,
    RELEASE_TIME TEXT,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID),
    FOREIGN KEY (CHRISTIAN_ID) REFERENCES CHRISTIANS(ID),
    FOREIGN KEY (COP_ID) REFERENCES COPS(ID)
);

CREATE TABLE TEAMS(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE GAME_TEAMS(
    ID INTEGER PRIMARY KEY,
    GAME_ID INTEGER NOT NULL,
    TEAM_ID INTEGER NOT NULL,
    POINTS INTEGER NOT NULL DEFAULT 0,
    WON INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)
);

CREATE TABLE PLAYER_TEAMS(
    GAME_TEAM_ID INTEGER NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    PRIMARY KEY (GAME_TEAM_ID, PLAYER_ID),
    FOREIGN KEY (GAME_TEAM_ID) REFERENCES GAME_TEAMS(ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES CHRISTIANS(ID)
);
