CREATE TABLE CHRISTIANS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    IMAGE TEXT,
    IN_JAIL INTEGER NOT NULL
);

CREATE TABLE COPS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    IMAGE TEXT
);

CREATE TABLE GAMES(
    ID INTEGER PRIMARY KEY NOT NULL,
    MODE TEXT NOT NULL,
    JAIL_START INTEGER NOT NULL,
    JAIL_INCREMENT INTEGER,
    JAIL_MAX INTEGER,
    START_TIME TEXT,
    END_TIME TEXT
);

CREATE TABLE CURRENT_GAME(
    ID INTEGER PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID) REFERENCES GAMES(ID)
);

CREATE TABLE CAPTURES(
    ID INTEGER PRIMARY KEY NOT NULL,
    GAME_ID INTEGER NOT NULL,
    CHRISTIAN_ID INTEGER,
    COP_ID INTEGER,
    CAPTURE_TIME TEXT,
    RELEASE_TIME TEXT,
    EARLY_RELEASE_TIME TEXT,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID),
    FOREIGN KEY (CHRISTIAN_ID) REFERENCES CHRISTIANS(ID),
    FOREIGN KEY (COP_ID) REFERENCES COPS(ID)
);
